name: Generate Snake

on:
  schedule:
    # Run at 5:00 AM every day
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: kondareddy1209
          outputs: dist/snake.svg

      # Upload the snake.svg to the repository
      - name: Push the Snake
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "GitHub Action"
          author_email: "action@github.com"
          message: "Add the snake animation"
          add: "dist/snake.svg"

