# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake

# Controls when the action will run.
on:
  schedule:
    # every 12 hours - FIXED: correct syntax
    - cron: "0 */12 * * *"
  
  # Allows running the Action manually from the Actions tab.
  workflow_dispatch:
  
  # Also run on every push to the main branch
  push:
    branches:
      - main
      - master

# The sequence of runs in this workflow:
jobs:
  # Single job called "build" 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Add permissions for the job
    permissions:
      contents: write
    
    # Steps represent a sequence of tasks executed in this job
    steps:
      # Step 1: Clone the repo
      - name: Clone repo
        uses: actions/checkout@v3
    
      # Step 2: Generate the snake files in the './dist/' directory
      - name: Generate the snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Kondareddy1209  # Your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
      # Step 3: Push new files to the output branch
      - name: Push snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animations"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
